// <auto-generated />
namespace Dota2ProTrend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class foreignkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foreignkey));
        
        string IMigrationMetadata.Id
        {
            get { return "201402280408051_foreignkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
