// <auto-generated />
namespace Dota2ProTrend.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class itemurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(itemurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201402282100019_itemurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
